name: Tests

on: [push, pull_request]

jobs:
  singularity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt install singularity-container
        sudo singularity build impr.sif singularity.def
    - run: |
        singularity exec impr.sif python -c 'import iris; print(iris.__version__)' 
