name: Tests

on: [push, pull_request]

jobs:

  singularity:
    name: Singularity container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Container image cache
      id: sif-cache
      uses: actions/cache@v1
      with:
        path: imprsif
        key: ${{ runner.os }}-${{ hashFiles('singularity.def') }}-${{ hashfiles('environment.yml') }}
    - name: Package installation
      if: steps.sif-cache.outputs.cache-hit != 'true'
      run: sudo apt-get install singularity-container
    - name: Container build
      if: steps.sif-cache.outputs.cache-hit != 'true'
      run: sudo singularity build impr.sif singularity.def
    - name: Container check
      if: steps.sif-cache.outputs.cache-hit != 'true'
      run: singularity exec impr.sif python -c 'import iris; print(iris.__version__)'
    - name: Container image split
      if: steps.sif-cache.outputs.cache-hit != 'true'
      run: mkdir imprsif; split --bytes=100M impr.sif imprsif/sifpart; rm impr.sif

  pytest:
    name: Pytest
    needs: singularity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Container image cache
      uses: actions/cache@v1
      with:
        path: imprsif
        key: ${{ runner.os }}-${{ hashFiles('singularity.def') }}-${{ hashfiles('environment.yml') }}
    - name: Container image setup
      run: cat imprsif/sifpart* > impr.sif; rm -r imprsif
    - name: Package installation
      run: sudo apt-get install singularity-container
    - name: Pytest
      run: singularity exec impr.sif pytest

  pycodestyle:
    name: Pycodestyle
    needs: singularity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Container image cache
      uses: actions/cache@v1
      with:
        path: imprsif
        key: ${{ runner.os }}-${{ hashFiles('singularity.def') }}-${{ hashfiles('environment.yml') }}
    - name: Container image setup
      run: cat imprsif/sifpart* > impr.sif; rm -r imprsif
    - name: Package installation
      run: sudo apt-get install singularity-container
    - name: Pycodestyle
      run: singularity exec impr.sif pycodestyle improver improver_tests
